version: '3'
services:
  nginx:
      build: ./openresty
      container_name: ciyo_nginx
      volumes:
        - ~/Work:/data1
        - ~/Work/htdocs/ciyo-dockers/openresty/conf.d:/etc/nginx/conf.d/
        - ~/Work/htdocs/ciyo-dockers/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      restart: always
      ports:
        - "80:80"