version: '3'
services:
  php_nginx:
      build: ./php5_nginx
      container_name: ciyo_php_nginx
      volumes:
        - ~/Work:/data1
        - ~/Work/htdocs/ciyo-dockers/php5_nginx/nginx/sites-enabled:/usr/local/nginx/conf/servers
        - ~/Work/htdocs/ciyo-dockers/php5_nginx/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
        - ~/Work/htdocs/ciyo-dockers/php5_nginx/php5/etc/php-fpm.conf:/usr/local/php5/etc/php-fpm.conf
      privileged: true
      restart: always
      ports:
        - "80:80"
      links:
        - mysql:mysql
        - memcached:memcached
        - redis_db:redis_db
        - redis_cache:redis_cache
        # - rabbitmq:rabbitmq
  mysql:
      build: ./mysql
      container_name: ciyo_mysql
      volumes:
        - ~/Work/data/mysql:/var/lib/mysql
        - ~/Work/log:/data1/log
      privileged: true
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      restart: always
      ports:
        - "3306:3306"
  memcached:
      image: memcached:1.4
      container_name: ciyo_memcached
      restart: always
      ports:
        - "11211:11211"
  redis_db:
      build: ./redis_db
      container_name: ciyo_redis_db
      volumes:
        - ~/Work/data/redis_db:/data
        - ~/Work/log:/data1/log
      privileged: true
      restart: always
      ports:
        - "6379:6379"
  redis_cache:
      build: ./redis_cache
      container_name: ciyo_redis_cache
      volumes:
        - ~/Work/log:/data1/log
      privileged: true
      restart: always
      ports:
        - "6380:6380"
  # rabbitmq:
  #     image: rabbitmq:3.1.5-management
  #     container_name: ciyo_rabbitmq
  #     restart: always
  #     ports:
  #       - "5672:5672"